#!/bin/bash

echo
echo "Validating types and linting..."
echo

yarn pr-check
validationStatus=$?

if [ $validationStatus -ne 0 ]; then
    echo
    echo "Error ❌ - commit validation failed"
    echo
    exit 1
fi

echo
echo "Success ✅ - commit validation passed - committing..."
echo

exit 0